### ISSUE TITLE
FAILED initialization

### ISSUE THREAD

**Issue by debjyotiC** [mjmeli/arduino-ad5933#5]
After uploading the code to an Arduino UNO, Started appears in the serial monitor shortly after which FAILED Initialization appears. I can't understand where the error is.

**Comment by Monzurul-1** [comment]
I faced similar situation. It was solved when i put the start freq at 1000 or less !

**Comment by AphroditeJoker** [comment]
It is because the Arduino Uno only has 2 byte for int, whose maximum is 32676. And that is approximately 2kHz I believe. If you do unsigned int I think it can goes up to 4kHz. If you wanna go higher than that you need a Arduino that has a SAMD chip on it(For example, Arduino Due). It will gives you 4 bytes int and you should be able to do 100kHz.

**Comment by jhschwartz** [comment]
I think my pull request #11 might fix the problem here.

**Comment by mjmeli** [comment]
Should be resolved by #11
